name: Sync Gdrive
        uses: actions/checkout@v4
          
      - name: Download Gclone
        run: |
          wget https://api.github.com/repos/dogbutcat/gclone/releases/latest -O - | awk -F \" -v RS="," '/browser_download_url/ {print $(NF-1)}' | grep 'linux-amd64.zip' | xargs wget
          unzip ./gclone-*-linux-amd64.zip
          cd ./gclone-*-linux-amd64
          chmod +x ./gclone
          sudo cp ./gclone /bin
      - name: Sync Gdrive
        run: |
          mkdir -p ~/.config/rclone/
          touch ~/.config/rclone/rclone.conf
          cat rclone.conf | sed -e "s@ACCESS_TOKEN@${ACCESS_TOKEN}@g" -e "s@REFRESH_TOKEN@${REFRESH_TOKEN}@g" -e "s@CLIENT_ID@${CLIENT_ID}@g" -e "s@CLIENT_SECRET@${CLIENT_SECRET}@g" > ~/.config/rclone/rclone.conf
          ARRAY_SAVE_FIELD_ID=($(echo ${SAVE_FIELD_ID}))
          gclone -vv sync drive:{$SHARE_FIELD_ID} drive:{${ARRAY_SAVE_FIELD_ID[3]}} --drive-server-side-across-configs

###############################################################################################################################################################################

  Sync_Gdrive_004:
    name: Sync_Gdrive_004
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Download Gclone
        run: |
          wget https://api.github.com/repos/dogbutcat/gclone/releases/latest -O - | awk -F \" -v RS="," '/browser_download_url/ {print $(NF-1)}' | grep 'linux-amd64.zip' | xargs wget
          unzip ./gclone-*-linux-amd64.zip
          cd ./gclone-*-linux-amd64
          chmod +x ./gclone
          sudo cp ./gclone /bin
      - name: Sync Gdrive
        run: |
          mkdir -p ~/.config/rclone/
          touch ~/.config/rclone/rclone.conf
          cat rclone.conf | sed -e "s@ACCESS_TOKEN@${ACCESS_TOKEN}@g" -e "s@REFRESH_TOKEN@${REFRESH_TOKEN}@g" -e "s@CLIENT_ID@${CLIENT_ID}@g" -e "s@CLIENT_SECRET@${CLIENT_SECRET}@g" > ~/.config/rclone/rclone.conf
          ARRAY_SAVE_FIELD_ID=($(echo ${SAVE_FIELD_ID}))
          gclone -vv sync drive:{$SHARE_FIELD_ID} drive:{${ARRAY_SAVE_FIELD_ID[4]}} --drive-server-side-across-configs

###############################################################################################################################################################################

  Sync_Gdrive_005:
    name: Sync_Gdrive_005
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Download Gclone
        run: |
          wget https://api.github.com/repos/dogbutcat/gclone/releases/latest -O - | awk -F \" -v RS="," '/browser_download_url/ {print $(NF-1)}' | grep 'linux-amd64.zip' | xargs wget
          unzip ./gclone-*-linux-amd64.zip
          cd ./gclone-*-linux-amd64
          chmod +x ./gclone
          sudo cp ./gclone /bin
      - name: Sync Gdrive
        run: |
          mkdir -p ~/.config/rclone/
          touch ~/.config/rclone/rclone.conf
          cat rclone.conf | sed -e "s@ACCESS_TOKEN@${ACCESS_TOKEN}@g" -e "s@REFRESH_TOKEN@${REFRESH_TOKEN}@g" -e "s@CLIENT_ID@${CLIENT_ID}@g" -e "s@CLIENT_SECRET@${CLIENT_SECRET}@g" > ~/.config/rclone/rclone.conf
          ARRAY_SAVE_FIELD_ID=($(echo ${SAVE_FIELD_ID}))
          gclone -vv sync drive:{$SHARE_FIELD_ID} drive:{${ARRAY_SAVE_FIELD_ID[5]}} --drive-server-side-across-configs

###############################################################################################################################################################################

  Sync_Gdrive_006:
    name: Sync_Gdrive_006
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Download Gclone
        run: |
          wget https://api.github.com/repos/dogbutcat/gclone/releases/latest -O - | awk -F \" -v RS="," '/browser_download_url/ {print $(NF-1)}' | grep 'linux-amd64.zip' | xargs wget
          unzip ./gclone-*-linux-amd64.zip
          cd ./gclone-*-linux-amd64
          chmod +x ./gclone
          sudo cp ./gclone /bin
      - name: Sync Gdrive
        run: |
          mkdir -p ~/.config/rclone/
          touch ~/.config/rclone/rclone.conf
          cat rclone.conf | sed -e "s@ACCESS_TOKEN@${ACCESS_TOKEN}@g" -e "s@REFRESH_TOKEN@${REFRESH_TOKEN}@g" -e "s@CLIENT_ID@${CLIENT_ID}@g" -e "s@CLIENT_SECRET@${CLIENT_SECRET}@g" > ~/.config/rclone/rclone.conf
          ARRAY_SAVE_FIELD_ID=($(echo ${SAVE_FIELD_ID}))
          gclone -vv sync drive:{$SHARE_FIELD_ID} drive:{${ARRAY_SAVE_FIELD_ID[6]}} --drive-server-side-across-configs

###############################################################################################################################################################################


