name: Single Sync Gdrive
on:
  workflow_dispatch:
  push:
  
env:
  dynv6_HTTP_Tokens: ${{ secrets.dynv6_HTTP_Tokens }}
jobs:
  delete-old-workflow-runs:
    name: delete-old-workflow-runs
    runs-on: ubuntu-latest
    permissions:
      actions: write
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: laoon2022/drive
          older-than-seconds: 60
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Sync_Gdrive_000:
    name: Sync_Gdrive_000
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add_Dynv6_Domain
        run: |
        
          response="$(curl -sS --fail -w "%{http_code}" https://dynv6.com/api/v2/zones \
           -H "Authorization: Bearer ${dynv6_HTTP_Tokens}" \
           -H "Content-Type: application/json" \
           -H "Accept: application/json")"

          # 解析区域信息
          response="${response:0:-3}"
          zone_ids_info="$(jq -r '.[] | "\(.id) \(.name)"' <<< $response)"
          echo "$zone_ids_info"
         
          # for domain in $(cat 001) ; do \
              # curl -sS --fail -w "%{http_code}" https://dynv6.com/api/v2/zones \
              #     -H "Authorization: Bearer ${dynv6_HTTP_Tokens}" \
              #     -H "Content-Type: application/json" \
              #     -H "Accept: application/json" \
              #     --data '{"name": "'${domain}'"}' || true  # 继续执行，即使curl失败



              
          # done




















            
